# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('article_user_name', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20, null=True)),
                ('content', models.TextField(default='')),
                ('commend', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('content', models.CharField(max_length=500)),
                ('comment_user_name', models.CharField(max_length=20)),
                ('commend', models.IntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=20, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(1, '管理员'), (2, '用户'), (3, '游客')])),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
