# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
