# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-07 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image_name',
            field=models.CharField(max_length=500),
        ),
    ]
