# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181108_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
    ]
